### ISSUE TITLE
Map view

### ISSUE THREAD

**Issue by chill117** [Learn-by-doing/generic-geotagging-app#2]
Create map view in app.
* The first view that is shown when the app is opened
* Full screen
* Display map using open street maps data

References:
* https://www.openstreetmap.org/
* https://switch2osm.org/using-tiles/getting-started-with-leaflet/

**Comment by vstoyanov** [comment]
We are going to handle this (Vasil Stoyanov + Jonathan Schurman).

**Comment by vstoyanov** [comment]
We are done with it. We had to use [react-native-maps](https://github.com/react-community/react-native-maps) however. What is the Git workflow for pushing the changes ?

**Comment by chill117** [comment]
We use the fork-branch-pull-request flow. Here's a guide that can help walk you through the steps:
https://gist.github.com/Chaser324/ce0505fbed06b947d962
