### ISSUE TITLE
Map view: Add item

### ISSUE THREAD

**Issue by chill117** [Learn-by-doing/generic-geotagging-app#4]
* [x] UI button to add item
* [x] When the button is pressed, an item icon should be placed on the map (at the center of the view).
* [x] ~The user should be able to drag the map around (under the item's icon) to re-position the item.~ (moved to separate issue)
* [x] A second UI button to finish setting the new item's location ("Done")

**Comment by dancunder** [comment]
Ok. I will take a shot at this one.

**Comment by dancunder** [comment]
Ok, I am still struggling to get the foundation done:
1. Installed react.native framework
2. created the app in the framework
3. pulled our sourcecode from here over it (lot of hassle)
4. installed the android studio and framework, but it is really not easy on windows it seems. The commands you have shared are simply not executing. I have to do the virtual machine in the avd part of the studio. It is giving me a lot of errors even when trying to run a generic emulator from the predefined ones.
5. didnt manage to run our app in the emulator yet.

**Comment by dancunder** [comment]
ok, git pull --allow-unrelated-histories did the magic

**Comment by chill117** [comment]
Done (mostly)
