### ISSUE TITLE
[IPFS] Research

### ISSUE THREAD

**Issue by RobinCsl** [Learn-by-doing/generic-geotagging-app#9]
We would like to use the Inter Planetary File System to store _the data_, whatever it may be.

# Some links to get started
Here are a few things to get started:
* This guy seems to have hosted a website; it roughly explains how DNSing would work with IPFS and how you would want some fixed _URLs_ for different versions of the files: https://medium.com/a-weekend-with/a-weekend-with-ipfs-9f2647fc231
* This is a follow-up discussion about the aforementioned article: https://discuss.ipfs.io/t/a-weekend-with-ipfs-by-will-hill/843
* Nice Gist about deploying a website through IPFS: https://gist.github.com/claus/1287f47b5fbaaea338ac8a04d02bf258
* IPFS docs: https://ipfs.io/docs/
* Some resource to understand the whitepaper behing IPFS: http://decentralized.blog/understanding-the-ipfs-white-paper-part-1.html

# First observations
Right now, there might not be advantages regarding speed of transfer as CDNs and HTTP2 are doing a good job. However, the decentralized aspect of IPFS could constitute a backup system in case CDNs were trying to censor your website.

**Comment by RobinCsl** [comment]
Many projects are being built on IPFS, as seen in [here](https://github.com/ipfs/awesome-ipfs).

**Comment by chill117** [comment]
https://ipfs.io/docs/getting-started/
